-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'EXAM_CLOSING_SOON';
ALTER TYPE "NotificationType" ADD VALUE 'EXAM_CLOSED_SUMMARY';
ALTER TYPE "NotificationType" ADD VALUE 'GROUP_BANK_BLOCKED';
ALTER TYPE "NotificationType" ADD VALUE 'GROUP_QUESTION_DISABLED';
ALTER TYPE "NotificationType" ADD VALUE 'CURRICULUM_BUMPED';
